### ISSUE TITLE
Newbie Needs Help

### ISSUE THREAD

**Issue by MaiMaeMay** [Scysta/pink-panic.nvim#2]
Hello, I'm very new to Rstudio and wanna change the appearance to your very cute theme. Is there any way to change the vim plug to something that's easier to download and just add onto Rstudio?

**Comment by Scysta** [comment]
Hi! I'm glad you like my theme. I don't have experience with rstudio, but I think Lush has a way to export colorschemes to more general formats. If you give me some time I could do some research and see if I can figure it out.

**Comment by MaiMaeMay** [comment]
That’s so sweet of you and would be much appreciated, thank you for the help <3

**Comment by Scysta** [comment]
Hi again. I think I managed to create a tmtheme file with the colours from my theme, or at least as close as I could replicate them. I don't even know if it works correctly lol, or if something else can be customized. Please try it out and see if it works for you!

[Pink-Panic.zip](https://github.com/Scysta/pink-panic.nvim/files/12908681/Pink-Panic.zip)

In any case, in here are the objects that can be modified inside RStudio https://rstudio.github.io/rstudio-extensions/rstudio-theme-creation.html. I hope it's not outdated. And I used this app to create the theme https://tmtheme-editor.glitch.me/, so if something looks off you can upload the file there and modify it however you like. Hope I was of help!

**Comment by MaiMaeMay** [comment]
Thank you so much! Me and my friend love it, it looks gorgeous hehe <3
